<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <ProjectReference Include="..\BPMS.Shared\BPMS.Shared.csproj" />
  </ItemGroup>

</Project>